# Generated by Django 2.0.2 on 2019-03-16 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(verbose_name='Date posted')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.IntegerField(default=5148896686)),
                ('becameMember', models.DateTimeField(verbose_name='Date joined')),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='listings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradePlatform.User'),
        ),
    ]
