# Generated by Django 2.0.2 on 2019-03-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradePlatform', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
    ]
