# Generated by Django 2.1.7 on 2019-03-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradePlatform', '0002_auto_20190316_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(max_length=15),
        ),
    ]
